deploymentGroup: prod
image:
  repository: 156013518325.dkr.ecr.us-west-2.amazonaws.com/sophtron/svc-search
  version:  "20230701ARM0"

app:
  name: sph-search
  fullName: sophtron-search
  requireAuth: true
  containerPort: 8080

service:
  port: 8080
  minReplicas: 2
  maxReplicas: 10
  healthcheck:
    port: 8080
  
resources:
  requests:
    cpu: 200m
    memory: 512Mi

ingress:
  zone: "sophtron"
  internalSubdomain: "search-int."
  public: true
  paths:
    - path: /api/institution
      type: Prefix
      public: true
      subdomain: "search." 
    - path: /
      type: Prefix
      subdomain: "search." #must include trailing period "." if not empty
env: 
  Port: "8080"
  LogLevel: "Debug" #"Warning" #"Info" "Debug"
  statsDHost: "statsd.sophtron-prod.com"
  AwsRegion: 'us-west-2'
  S3Bucket: 'sophtron-prod-data'
  SophtronAnalyticsServiceEndpoint: 'http://sph-analytics-service-prod:8080/api/'
  RedisServer: 'redis://redis.sph-eks.svc.cluster.local:6379'
  
secrets:
  DataBucketAccessKey: 'data-bucket-key'
  DataBucketAccessKeyId: 'data-bucket-key-id'

