
name: 'E2E Tests'

on: pull_request

jobs:
  setup-env:
    name: 'Load ENV Vars'
    uses: ./.github/workflows/setup-env.yml
    secrets: inherit

  e2e-tests:
    name: 'E2E FTW'
    runs-on: ubuntu-latest
    needs: [setup-env]

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
      - run: npm ci

      - name: 'Create env file'
        run: |
          touch .env
          
          # Vars
          echo -e "${{ needs.setup-env.outputs.env_vars }}" >> .env
          echo VERSION="" >> .env
          echo "${{ needs.setup-env.outputs.env_vars }}" >> $GITHUB_ENV

      - name: 'Cypress run'
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: "http://localhost:8082/ping"
