name: Unit/Integration tests

on: pull_request

jobs:
  setup-env:
    name: 'Load ENV Vars'
    uses: ./.github/workflows/setup-env.yml
    secrets: inherit

  run-jest-tests:
    name: Jest Tests
    runs-on: ubuntu-latest
    needs: [setup-env]

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          check-latest: true

      - name: Install all dependencies
        run: |
          npm ci

      - name: 'Create env file'
        run: |
          touch .env
          
          # Vars
          #echo -e ${{ needs.setup-env.outputs.env_vars }} >> .env
          echo "${{ needs.setup-env.outputs.env_vars }}" >> $GITHUB_ENV

      - name: Run Jest Tests
        run: |
          npx jest --all --ci